---
rbac:
  create: true
  createRole: false
  createClusterRole: false

controller:
  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.3.4
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-LB-subnet
      service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-aks-nodepool-rg
    ports:
      - port: 80
      - port: 443
      