# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{ if .Values.wso2.deployment.persistence.solrIndexing.enabled }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-all-in-one.fullname" . }}-am-carbon-database
  namespace : {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistence.solrIndexing.capacity.carbonDatabase }}
  selector:
    matchLabels:
      purpose: am-carbondb
  storageClassName: {{ template "am-all-in-one.fullname" . }}-am-sc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-all-in-one.fullname" . }}-solr-indexed-data
  namespace : {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistence.solrIndexing.capacity.solrIndexedData }}
  selector:
    matchLabels:
      purpose: am-solr
  storageClassName: {{ template "am-all-in-one.fullname" . }}-am-sc
{{- end }}
