# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{ if and .Values.wso2.deployment.persistence.solrIndexing.enabled .Values.azure.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "am-all-in-one.fullname" . }}-am-sc
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid={{ .Values.kubernetes.securityContext.runAsUser }}
 - gid={{ .Values.kubernetes.securityContext.runAsUser }}
 - cache=strict
parameters:
  skuName: {{  .Values.azure.persistence.storageAccountType }}
{{ end }}
